### ISSUE TITLE
Wrong Notification number

### ISSUE THREAD

**Issue by MarcelHue** [wassimbj/cleverSnakeGame#1]
when completing in the message there is the wrong number of level

**Comment by wassimbj** [comment]
Hello, thanks for opening an issue, can you elaborate more please ? for now the game has 5 levels only

**Comment by MarcelHue** [comment]
If you beat the 5. Level you get the push msg that there are only 3 levels currently, so I think the notification was not updated when new levels were added.

**Comment by wassimbj** [comment]
aah, thank you so much, i'll fix it
